import {useEffect,useMemo,useState} from 'react'
import {Zap,Search,ExternalLink,RefreshCw,ShieldCheck,Flame,Activity} from 'lucide-react'
const META=t=>`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q=${encodeURIComponent(t)}&search_type=keyword_unordered`
const SEEDS=[
 ['acesso imediato','Infoproduto'],['curso online','Infoproduto'],['método exclusivo','Infoproduto'],['treinamento completo','Infoproduto'],['passo a passo','Infoproduto'],['aula gratuita','Infoproduto'],
 ['R$ 97','Preço'],['R$ 197','Preço'],['12x de','Preço'],['por apenas','Preço'],['garantia de 7 dias','Conversão'],['clique em saiba mais','Conversão'],
 ['últimas vagas','Urgência'],['inscrições abertas','Urgência'],['aprenda como','Transformação'],['sem precisar','Mecanismo'],['planilha pronta','Digital'],['template','Digital']
]
function tier(s){return s>=85?'🔥 Prioridade máxima':s>=75?'🟢 Forte candidato':s>=62?'🔵 Investigar':'Observação'}
export default function DiscoveryEngine(){
 const[items,setItems]=useState([]),[updated,setUpdated]=useState(null)
 function load(){window.postMessage({type:'OFERTA_RADAR_REQUEST_DISCOVERY'},'*')}
 useEffect(()=>{const h=e=>{if(e.data?.type==='OFERTA_RADAR_DISCOVERY'){setItems(e.data.payload||[]);setUpdated(new Date())}};window.addEventListener('message',h);load();const t=setInterval(load,5000);return()=>{clearInterval(t);window.removeEventListener('message',h)}},[])
 const best=useMemo(()=>[...items].sort((a,b)=>(b.score||0)-(a.score||0)),[items])
 return <div>
  <section className="rounded-3xl border border-zinc-800 bg-gradient-to-br from-emerald-950/30 via-zinc-900/80 to-zinc-950 p-6 shadow-2xl shadow-black/20"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-emerald-400/20 bg-emerald-400/10"><Zap className="h-5 w-5 text-emerald-300"/></div><div><h2 className="text-xl font-bold">Motor de Descoberta</h2><p className="text-[11px] text-zinc-500">Meta Ads Library → triagem automática → melhores candidatos</p></div></div><p className="mt-4 max-w-4xl text-sm leading-relaxed text-zinc-400">Abra uma pesquisa na Biblioteca da Meta e ative <b className="text-zinc-200">⚡ Motor de Descoberta</b> na extensão. Ela desce a página automaticamente, observa os anúncios carregados e envia ao painel somente candidatos com sinais fortes.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-xs text-zinc-300"><RefreshCw className="h-3.5 w-3.5"/>Atualizar candidatos</button></div></section>
  <div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-4"><b className="text-2xl">{best.length}</b><div className="text-[10px] uppercase text-zinc-600">melhores retidos</div></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-4"><b className="text-2xl text-emerald-300">{best.filter(x=>(x.score||0)>=75).length}</b><div className="text-[10px] uppercase text-zinc-600">enviados à caixa</div></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-4"><b className="text-2xl">{best.filter(x=>(x.days||0)>=30).length}</b><div className="text-[10px] uppercase text-zinc-600">30+ dias</div></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-4"><b className="text-2xl">{best.filter(x=>(x.metaVariants||0)>=3).length}</b><div className="text-[10px] uppercase text-zinc-600">3+ variações</div></div></div>
  <section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900/45 p-5"><h3 className="text-sm font-bold">Pesquisas para iniciar uma sessão</h3><p className="mt-1 text-[11px] text-zinc-500">Abra uma delas, inicie o motor na extensão e deixe a página carregar. Não é necessário selecionar anúncio por anúncio.</p><div className="mt-3 flex flex-wrap gap-2">{SEEDS.map(([q,k])=><a key={q} href={META(q)} target="_blank" rel="noreferrer" className="rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-2 text-[10px] text-blue-300 hover:border-blue-400/30"><span className="mr-2 text-zinc-600">{k}</span>{q}</a>)}</div></section>
  <div className="mt-5 grid gap-4 xl:grid-cols-2">{best.map(x=><article key={x.libraryId} className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-5"><div className="flex gap-4">{x.images?.[0]&&<img src={x.images[0]} className="h-24 w-28 rounded-xl object-cover"/>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><div className={`text-[10px] font-bold uppercase tracking-wider ${(x.score||0)>=75?'text-emerald-300':'text-blue-300'}`}>{tier(x.score||0)}</div><h3 className="mt-1 truncate font-bold">{x.pageName}</h3><div className="mt-1 text-[10px] text-zinc-600">ID {x.libraryId} • busca: {x.searchQuery||'—'}</div></div><div className="rounded-xl bg-zinc-950 px-3 py-2 text-2xl font-black">{x.score}</div></div><div className="mt-4 grid grid-cols-4 gap-2 text-center"><div><b>{x.days??'—'}</b><div className="text-[9px] text-zinc-600">dias</div></div><div><b>{x.metaVariants||1}</b><div className="text-[9px] text-zinc-600">variações</div></div><div><b>{x.images?.length||0}</b><div className="text-[9px] text-zinc-600">mídias</div></div><div><b>{x.hasVideo?'sim':'—'}</b><div className="text-[9px] text-zinc-600">vídeo</div></div></div></div></div><div className="mt-4 flex gap-2"><a href={`https://www.facebook.com/ads/library/?id=${x.libraryId}`} target="_blank" rel="noreferrer" className="flex-1 rounded-xl bg-blue-500/10 px-3 py-2.5 text-center text-xs font-bold text-blue-300">Abrir anúncio</a>{x.destinations?.[0]&&<a href={x.destinations[0]} target="_blank" rel="noreferrer" className="rounded-xl border border-zinc-800 px-3 py-2.5 text-zinc-400"><ExternalLink className="h-4 w-4"/></a>}</div></article>)}</div>
  {!best.length&&<div className="mt-5 rounded-2xl border border-dashed border-zinc-800 py-16 text-center"><Zap className="mx-auto h-8 w-8 text-zinc-700"/><p className="mt-3 text-sm text-zinc-600">Nenhum candidato automático ainda.</p><p className="mt-1 text-[11px] text-zinc-700">Abra uma pesquisa acima e ligue o Motor de Descoberta na extensão.</p></div>}
  <p className="mt-5 text-[10px] leading-relaxed text-zinc-600"><ShieldCheck className="mr-1 inline h-3 w-3"/>O motor apenas rola a página e lê anúncios que a Biblioteca já carregou. Score representa evidência observável, não faturamento ou ROAS.</p>
 </div>
}