import {useEffect,useMemo,useState} from 'react'
import {TrendingUp,CalendarDays,RefreshCw,Target,Star,Brain,Search,ChevronRight} from 'lucide-react'

const META=t=>`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q=${encodeURIComponent(t)}&search_type=keyword_unordered`
const TRENDS=t=>`https://trends.google.com/trends/explore?geo=BR&q=${encodeURIComponent(t)}`
const MONTH=new Date().getMonth()+1
const OPPS=[
 {name:'Black Friday',months:[9,10,11],peak:'Novembro',base:96,kind:'Varejo',why:'Anunciantes começam testes antes do pico; procure operações antigas recebendo criativos novos.',words:['black friday','50% de desconto','70% de desconto','frete grátis','compre 1 leve 2','últimas unidades']},
 {name:'Natal & Presentes',months:[10,11,12],peak:'Novembro–Dezembro',base:94,kind:'Presentes',why:'Alta intenção de compra e muitos produtos demonstráveis; antecipação ajuda a separar teste de escala.',words:['presente de natal','presente personalizado','presente para mulher','presente para homem','frete grátis','kit presente']},
 {name:'Dia das Crianças',months:[8,9,10],peak:'Setembro–Outubro',base:91,kind:'Infantil',why:'Janela curta e comercial. Procure brinquedos/produtos com demonstração visual e renovação de criativos.',words:['presente criança','brinquedo educativo','presente menina','presente menino','compre 1 leve 2','frete grátis']},
 {name:'Casa & Organização',months:[1,2,3,4,5,6,7,8,9,10,11,12],peak:'Ano todo',base:82,kind:'Evergreen',why:'Problemas visuais simples permitem criativos demonstrativos e ofertas de baixo atrito.',words:['organizador','casa organizada','organizador cozinha','limpeza prática','facilita o dia a dia','compre 1 leve 2']},
 {name:'Automotivo',months:[1,2,3,4,5,6,7,8,9,10,11,12],peak:'Ano todo',base:84,kind:'Evergreen',why:'Acessórios resolvem dores específicas e são fáceis de demonstrar em vídeo.',words:['acessório automotivo','para seu carro','limpeza automotiva','organizador carro','proteção automotiva','frete grátis']},
 {name:'Pets',months:[1,2,3,4,5,6,7,8,9,10,11,12],peak:'Ano todo',base:81,kind:'Evergreen',why:'Apelo emocional e demonstração visual; filtre promessas exageradas e priorize utilidade concreta.',words:['produto para cachorro','produto para gato','pet shop online','acessório pet','pelos de cachorro','frete grátis']},
 {name:'Beleza & Autocuidado',months:[1,2,3,4,5,6,7,8,9,10,11,12],peak:'Ano todo',base:83,kind:'Evergreen',why:'Grande volume criativo; priorize produtos cosméticos/estéticos com benefício demonstrável e claims responsáveis.',words:['autocuidado','rotina de beleza','cuidado com cabelo','unhas','skincare','kit beleza']},
 {name:'Volta às Aulas',months:[12,1,2],peak:'Janeiro–Fevereiro',base:88,kind:'Sazonal',why:'Material, organização e rotina ganham intenção comercial antes do início das aulas.',words:['volta às aulas','material escolar','organizador escolar','etiqueta escolar','mochila escolar','kit escolar']},
 {name:'Verão',months:[10,11,12,1,2],peak:'Dezembro–Janeiro',base:85,kind:'Sazonal',why:'Antecipe produtos de viagem, praia, conforto e organização antes do pico.',words:['produto para verão','praia','viagem verão','organizador viagem','férias','kit viagem']}
]
const NOISE=/futebol|campeonato|jogo|placar|time|presidente|eleiç|deputad|senador|governo|morreu|morte|acidente|crime|prisão|novela|ator|atriz|cantor|celebridade|bbb|reality/i
const COMMERCIAL=/black friday|natal|presente|desconto|oferta|produto|compr|frete|loja|beleza|cabelo|unha|casa|cozinha|carro|automot|pet|cachorro|gato|escolar|viagem|praia|verão|organizador|limpeza|brinquedo|kit/i
const intent=t=>COMMERCIAL.test(t)?'Alta':'Baixa'
function moment(o){if(o.months.includes(MONTH)){const i=o.months.indexOf(MONTH);return i<=1?'Hora de pesquisar':'Hora de testar'}return 'Planejar'}
function oppScore(o){return Math.min(100,o.base+(o.months.includes(MONTH)?3:0))}
function extractPhrases(items){
 const stop=new Set('para com uma umas uns dos das que por seu sua seus suas mais como este esta essa esse não sim tem você seu anuncio anúncio agora aqui muito'.split(' '))
 const counts={}
 for(const x of items){
  const text=(x.adText||'').toLowerCase().replace(/[^\p{L}\p{N}\s%$]/gu,' ').replace(/\s+/g,' ').trim()
  const w=text.split(' ').filter(x=>x.length>2&&!stop.has(x))
  for(let n=2;n<=4;n++)for(let i=0;i<=w.length-n;i++){const p=w.slice(i,i+n).join(' ');if(p.length<8)continue;counts[p]=(counts[p]||0)+1}
 }
 return Object.entries(counts).filter(([,c])=>c>=2).sort((a,b)=>b[1]-a[1]).slice(0,25).map(([term,count])=>({term,count}))
}
export default function KeywordLab(){
 const[live,setLive]=useState([]),[loading,setLoading]=useState(false),[inbox,setInbox]=useState([]),[watch,setWatch]=useState(()=>{try{return JSON.parse(localStorage.getItem('ofertaRadarOpportunityWatch')||'[]')}catch{return[]}})
 const[tab,setTab]=useState('opportunities')
 async function load(){setLoading(true);try{const r=await fetch('/api/trends');const d=await r.json();setLive(d.items||[])}catch{}finally{setLoading(false)}}
 useEffect(()=>{load();const h=e=>{if(e.data?.type==='OFERTA_RADAR_INBOX')setInbox(e.data.payload||[])};window.addEventListener('message',h);window.postMessage({type:'OFERTA_RADAR_REQUEST_INBOX'},'*');return()=>window.removeEventListener('message',h)},[])
 const cleanLive=useMemo(()=>live.filter(x=>!NOISE.test(x.title)&&COMMERCIAL.test(x.title)),[live])
 const phrases=useMemo(()=>extractPhrases(inbox),[inbox])
 function toggle(name){const n=watch.includes(name)?watch.filter(x=>x!==name):[...watch,name];setWatch(n);localStorage.setItem('ofertaRadarOpportunityWatch',JSON.stringify(n))}
 return <div>
  <section className="rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/[.09] to-zinc-900/60 p-5">
   <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><Brain className="h-5 w-5 text-violet-400"/><h2 className="text-lg font-bold">Inteligência de Oportunidades</h2><span className="rounded bg-violet-500/15 px-2 py-1 text-[10px] font-bold text-violet-300">FASE 5.7</span></div><p className="mt-2 max-w-4xl text-xs leading-relaxed text-zinc-400">Menos notícia e mais intenção comercial. Cruze sazonalidade, palavras de compra e os anúncios que você próprio selecionou para descobrir onde vale minerar.</p></div><div className="flex rounded-xl border border-zinc-800 bg-zinc-950 p-1 text-xs"><button onClick={()=>setTab('opportunities')} className={`rounded-lg px-3 py-2 ${tab==='opportunities'?'bg-violet-500 text-white':'text-zinc-500'}`}>🔥 Oportunidades</button><button onClick={()=>setTab('phrases')} className={`rounded-lg px-3 py-2 ${tab==='phrases'?'bg-violet-500 text-white':'text-zinc-500'}`}>🧬 Palavras descobertas</button></div></div>
  </section>

  {tab==='opportunities'&&<><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><b className="text-2xl">{OPPS.filter(o=>o.months.includes(MONTH)).length}</b><div className="text-[10px] uppercase text-zinc-600">janelas ativas</div></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><b className="text-2xl">{watch.length}</b><div className="text-[10px] uppercase text-zinc-600">acompanhando</div></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><b className="text-2xl">{cleanLive.length}</b><div className="text-[10px] uppercase text-zinc-600">tendências comerciais agora</div></div></div>
   <div className="mt-4 grid gap-4 lg:grid-cols-2">{[...OPPS].sort((a,b)=>oppScore(b)-oppScore(a)).map(o=><article key={o.name} className="rounded-2xl border border-zinc-800 bg-zinc-900/55 p-5"><div className="flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-widest text-violet-400">{o.kind} • pico {o.peak}</div><h3 className="mt-1 text-lg font-bold">{o.name}</h3></div><div className="flex items-center gap-2"><div className="rounded-lg bg-emerald-400/10 px-2 py-1 text-lg font-black text-emerald-300">{oppScore(o)}</div><button onClick={()=>toggle(o.name)} className={`rounded-lg border p-2 ${watch.includes(o.name)?'border-amber-400/30 text-amber-300':'border-zinc-800 text-zinc-600'}`}><Star className="h-4 w-4" fill={watch.includes(o.name)?'currentColor':'none'}/></button></div></div><div className="mt-3 flex gap-2"><span className="rounded bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">{moment(o)}</span><span className="rounded bg-zinc-800 px-2 py-1 text-[10px]">Intenção comercial alta</span></div><p className="mt-3 text-xs leading-relaxed text-zinc-400">{o.why}</p><div className="mt-4 flex flex-wrap gap-1.5">{o.words.map(w=><a key={w} href={META(w)} target="_blank" rel="noreferrer" className="rounded-lg border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-[10px] text-blue-300 hover:border-blue-400/30">{w}</a>)}</div><div className="mt-4 flex gap-2"><a href={META(o.words[0])} target="_blank" rel="noreferrer" className="flex-1 rounded-xl bg-blue-500 px-3 py-2.5 text-center text-xs font-bold text-white">🎯 Minerar na Meta</a><a href={TRENDS(o.name)} target="_blank" rel="noreferrer" className="rounded-xl border border-zinc-700 px-3 py-2.5 text-xs font-bold text-emerald-300">📈 Trends</a></div></article>)}</div>

   <section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><div className="flex items-center justify-between"><div><h3 className="flex items-center gap-2 font-semibold"><TrendingUp className="h-4 w-4 text-emerald-400"/>Tendências comerciais filtradas</h3><p className="mt-1 text-xs text-zinc-500">O feed geral é filtrado para reduzir futebol, política, celebridades e notícias sem intenção comercial.</p></div><button onClick={load} className="rounded-lg border border-zinc-800 p-2"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>{cleanLive.length?<div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{cleanLive.slice(0,18).map(x=><div key={x.title} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><b className="text-sm">{x.title}</b><div className="mt-1 text-[10px] text-zinc-600">{x.traffic||'Tendência ativa'} • intenção {intent(x.title)}</div><div className="mt-2 flex gap-3"><a href={META(x.title)} target="_blank" rel="noreferrer" className="text-[10px] text-blue-300">Buscar anúncios</a><a href={TRENDS(x.title)} target="_blank" rel="noreferrer" className="text-[10px] text-emerald-300">Validar tendência</a></div></div>)}</div>:<div className="mt-4 rounded-xl border border-dashed border-zinc-800 py-8 text-center text-xs text-zinc-600">Nenhuma tendência geral passou pelo filtro comercial agora — isso é melhor do que preencher a tela com assuntos sem relação com ofertas.</div>}</section></>}

  {tab==='phrases'&&<section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-5"><div><h3 className="font-semibold">🧬 Palavras que seus anúncios estão ensinando</h3><p className="mt-1 max-w-3xl text-xs text-zinc-500">O Radar procura frases de 2–4 palavras repetidas nos anúncios que você enviou para a Caixa de Entrada. Quanto mais você selecionar ofertas boas, mais útil esta área fica.</p></div>
   <div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{phrases.map((p,i)=><div key={p.term} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-4"><div className="flex items-start justify-between"><div><div className="text-[10px] text-zinc-600">#{i+1} • encontrada {p.count}x</div><b className="mt-1 block">{p.term}</b></div><div className="rounded bg-violet-400/10 px-2 py-1 text-xs font-black text-violet-300">{Math.min(99,45+p.count*8)}</div></div><div className="mt-3 flex gap-2"><a href={META(p.term)} target="_blank" rel="noreferrer" className="flex-1 rounded-lg bg-blue-500/10 px-2 py-2 text-center text-[10px] font-bold text-blue-300">Minerar frase</a><a href={TRENDS(p.term)} target="_blank" rel="noreferrer" className="rounded-lg bg-emerald-500/10 px-2 py-2 text-[10px] text-emerald-300">Trends</a></div></div>)}</div>
   {!phrases.length&&<div className="mt-4 rounded-xl border border-dashed border-zinc-800 py-12 text-center text-xs text-zinc-600">Ainda não há frases repetidas suficientes. Envie mais anúncios interessantes pela extensão; com 10–30 seleções essa área começa a ganhar valor.</div>}
  </section>}
 </div>
}