import { useMemo, useState } from 'react'
import { Search, ExternalLink, ClipboardPaste, Trash2, Target, CalendarDays, Plus, X } from 'lucide-react'
const KEY='oferta-radar:meta-captures'
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
const metaUrl=q=>`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q=${encodeURIComponent(q)}&search_type=keyword_unordered`
const parse=(text,destination,variants)=>{const lines=text.split('\n').map(x=>x.trim()).filter(Boolean);const sponsored=lines.findIndex(x=>/Patrocinado|Sponsored/i.test(x));const item={id:crypto.randomUUID(),libraryId:text.match(/(?:Identificação da biblioteca|Library ID)[:\s]+(\d+)/i)?.[1]||'',startDate:text.match(/(?:Veiculação iniciada em|Started running on)\s+([^\n]+)/i)?.[1]?.trim()||'',pageName:sponsored>0?lines[sponsored-1]:'',destination:destination.trim(),variants:Number(variants)||1,notes:text,createdAt:new Date().toISOString()};let s=20+(item.libraryId?20:0)+(item.startDate?20:0)+(item.pageName?10:0)+(item.destination?15:0)+(item.notes.length>30?5:0)+(item.variants>=3?10:0);item.score=Math.min(100,s);return item}
export default function MetaHunt({candidates=[]}){
 const[term,setTerm]=useState('');const[captures,setCaptures]=useState(load);const[show,setShow]=useState(false);const[raw,setRaw]=useState('');const[dest,setDest]=useState('');const[variants,setVariants]=useState(1)
 const domains=useMemo(()=>{const s=new Set();return candidates.filter(x=>x.domain&&!s.has(x.domain)&&s.add(x.domain)).slice(0,12)},[candidates])
 const persist=n=>{setCaptures(n);localStorage.setItem(KEY,JSON.stringify(n))}
 const capture=()=>{if(!raw.trim()&&!dest.trim())return;persist([parse(raw.trim(),dest,variants),...captures]);setRaw('');setDest('');setVariants(1);setShow(false)}
 return <div>
  <section className="rounded-2xl border border-blue-400/20 bg-gradient-to-br from-blue-500/[.08] to-zinc-900/60 p-5">
   <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-2"><Target className="h-5 w-5 text-blue-400"/><h2 className="text-lg font-bold">Meta Hunt</h2><span className="rounded bg-blue-500/15 px-2 py-1 text-[10px] font-bold text-blue-300">FASE 3</span></div><p className="mt-2 text-xs leading-relaxed text-zinc-400">Caça assistida na Biblioteca de Anúncios da Meta. A API oficial não libera mineração geral de anúncios comerciais do Brasil; aqui você abre buscas oficiais e registra evidências reais sem inventar métricas.</p></div><button onClick={()=>setShow(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-4 py-3 text-xs font-bold text-white"><Plus className="h-4 w-4"/>Registrar anúncio encontrado</button></div>
   <div className="mt-5 flex flex-col gap-2 sm:flex-row"><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Produto, promessa, anunciante ou palavra-chave..." className="flex-1 rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-sm outline-none focus:border-blue-400/50"/><a href={term.trim()?metaUrl(term.trim()):'#'} onClick={e=>{if(!term.trim())e.preventDefault()}} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-5 py-3 text-sm font-bold text-white"><Search className="h-4 w-4"/>Buscar anúncios ativos</a></div>
  </section>
  {domains.length>0&&<section className="mt-4 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><h3 className="font-semibold">Fila de investigação na Meta</h3><p className="mt-1 text-xs text-zinc-500">Domínios descobertos pelo Web Radar para conferir na Biblioteca.</p><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{domains.map(x=><a key={x.domain} href={metaUrl(x.domain)} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-zinc-800 bg-zinc-950 px-3 py-3 hover:border-blue-400/30"><div className="min-w-0"><div className="truncate text-xs font-semibold">{x.domain}</div><div className="mt-1 text-[10px] text-zinc-600">Score web {x.miningScore??x.score} • {x.activityCount||1} ocorrência(s)</div></div><ExternalLink className="h-4 w-4 text-blue-400"/></a>)}</div></section>}
  <section className="mt-4"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-semibold">Anúncios registrados</h3><p className="mt-1 text-xs text-zinc-500">Sua base local de evidências da Biblioteca.</p></div><span className="text-xs text-zinc-600">{captures.length} registros</span></div>
  {captures.length?<div className="grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{captures.map(i=><article key={i.id} className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="flex justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-widest text-blue-400">Meta Ads Evidence</div><h4 className="mt-1 font-bold">{i.pageName||'Anunciante não identificado'}</h4></div><div className="rounded-lg bg-emerald-400/10 px-2 py-1 text-xs font-bold text-emerald-300">{i.score}/100</div></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-lg bg-zinc-950 p-3"><span className="text-zinc-600">Library ID</span><div className="mt-1 truncate">{i.libraryId||'—'}</div></div><div className="rounded-lg bg-zinc-950 p-3"><span className="text-zinc-600">Variações</span><div className="mt-1">{i.variants}</div></div></div>{i.startDate&&<div className="mt-2 flex items-center gap-2 text-xs text-zinc-400"><CalendarDays className="h-3.5 w-3.5 text-amber-400"/>{i.startDate}</div>}{i.destination&&<a href={i.destination} target="_blank" rel="noreferrer" className="mt-3 block truncate text-xs text-blue-400">{i.destination}</a>}<div className="mt-4 flex gap-2"><a href={metaUrl(i.pageName||i.destination||i.libraryId)} target="_blank" rel="noreferrer" className="flex-1 rounded-lg bg-blue-500/10 px-3 py-2 text-center text-xs font-semibold text-blue-300">Reabrir na Meta</a><button onClick={()=>persist(captures.filter(x=>x.id!==i.id))} className="rounded-lg border border-zinc-800 px-3 text-zinc-600 hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-12 text-center text-sm text-zinc-600">Faça uma busca na Meta e registre os anúncios promissores.</div>}</section>
  {show&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-2xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex justify-between"><div><h3 className="font-bold">Registrar anúncio da Meta</h3><p className="mt-1 text-xs text-zinc-500">Cole o texto do card/detalhes. Extraímos ID, anunciante e data quando presentes.</p></div><button onClick={()=>setShow(false)} className="p-2 text-zinc-500"><X className="h-4 w-4"/></button></div><textarea value={raw} onChange={e=>setRaw(e.target.value)} rows={9} placeholder="Cole aqui o conteúdo do anúncio..." className="mt-4 w-full rounded-xl border border-zinc-700 bg-zinc-900 p-3 text-sm outline-none"/><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_140px]"><input value={dest} onChange={e=>setDest(e.target.value)} placeholder="URL de destino (opcional)" className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-3 text-sm"/><input type="number" min="1" value={variants} onChange={e=>setVariants(e.target.value)} className="rounded-xl border border-zinc-700 bg-zinc-900 px-3 py-3 text-sm" title="Variações"/></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setShow(false)} className="rounded-xl border border-zinc-700 px-4 py-2.5 text-xs">Cancelar</button><button onClick={capture} className="inline-flex items-center gap-2 rounded-xl bg-blue-500 px-4 py-2.5 text-xs font-bold text-white"><ClipboardPaste className="h-4 w-4"/>Salvar evidência</button></div></div></div>}
 </div>
}