import {useEffect,useMemo,useState} from 'react'
import {Inbox,RefreshCw,ExternalLink,Trash2,Search,Copy,Clock3,Layers3,Image as ImageIcon,CheckCircle2} from 'lucide-react'

const metaSearch=q=>`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q=${encodeURIComponent(q)}&search_type=keyword_unordered`
export default function MetaInbox(){
 const[connected,setConnected]=useState(false),[items,setItems]=useState([]),[q,setQ]=useState('')
 const[dossiers,setDossiers]=useState(()=>{try{return JSON.parse(localStorage.getItem('ofertaRadarDossiers')||'{}')}catch{return{}}})
 const[analyzing,setAnalyzing]=useState(''),[detail,setDetail]=useState(null)
 useEffect(()=>{
  const h=e=>{
   if(e.data?.type==='OFERTA_RADAR_EXTENSION_READY'){setConnected(true);window.postMessage({type:'OFERTA_RADAR_REQUEST_INBOX'},'*')}
   if(e.data?.type==='OFERTA_RADAR_INBOX'){setConnected(true);setItems(Array.isArray(e.data.payload)?e.data.payload:[])}
  }
  window.addEventListener('message',h);window.postMessage({type:'OFERTA_RADAR_REQUEST_INBOX'},'*')
  return()=>window.removeEventListener('message',h)
 },[])
 const filtered=useMemo(()=>{const s=q.toLowerCase().trim();return !s?items:items.filter(x=>JSON.stringify(x).toLowerCase().includes(s))},[items,q])
 const remove=id=>window.postMessage({type:'OFERTA_RADAR_REMOVE_INBOX_ITEM',id},'*')
 async function investigate(x){
  const url=x.destinations?.[0]; if(!url)return alert('Não consegui extrair a landing deste anúncio. Abra o anúncio na Meta e tente um card com link de destino visível.')
  setAnalyzing(x.captureId)
  try{
   const r=await fetch('/api/analyze?url='+encodeURIComponent(url)); const d=await r.json()
   if(!r.ok)throw new Error(d.error||'Falha na análise')
   const dossier={...d,meta:{pageName:x.pageName,libraryId:x.libraryId,days:x.days,metaVariants:x.metaVariants,adScore:x.score,searchQuery:x.searchQuery,adText:x.adText},savedAt:new Date().toISOString()}
   const next={...dossiers,[x.captureId]:dossier};setDossiers(next);localStorage.setItem('ofertaRadarDossiers',JSON.stringify(next));setDetail(dossier)
  }catch(e){alert(e.message)}finally{setAnalyzing('')}
 }
 return <div>
  <section className="rounded-2xl border border-blue-400/20 bg-gradient-to-br from-blue-500/[.08] to-zinc-900/60 p-5">
   <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2"><Inbox className="h-5 w-5 text-blue-400"/><h2 className="text-lg font-bold">Caixa de Entrada Meta</h2><span className="rounded bg-blue-500/15 px-2 py-1 text-[10px] font-bold text-blue-300">FASE 5.5</span></div><p className="mt-2 max-w-3xl text-xs leading-relaxed text-zinc-400">Aqui chegam somente os anúncios que você selecionou na Biblioteca da Meta. É a sua fila de investigação, sem trazer centenas de resultados irrelevantes.</p></div><div className={`rounded-xl border px-3 py-2 text-xs font-bold ${connected?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':'border-amber-400/20 bg-amber-400/10 text-amber-300'}`}>{connected?'● Extensão conectada':'● Extensão não detectada'}</div></div>
   <div className="mt-5 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filtrar por anunciante, texto, palavra-chave..." className="flex-1 rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-sm outline-none"/><button onClick={()=>window.postMessage({type:'OFERTA_RADAR_REQUEST_INBOX'},'*')} className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-3 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Sincronizar</button></div>
  </section>
  <div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="text-2xl font-black">{items.length}</div><div className="mt-1 text-[10px] uppercase text-zinc-600">Na caixa</div></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="text-2xl font-black">{items.filter(x=>x.score>=75).length}</div><div className="mt-1 text-[10px] uppercase text-zinc-600">Escalando</div></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="text-2xl font-black">{items.filter(x=>x.days>=30).length}</div><div className="mt-1 text-[10px] uppercase text-zinc-600">30+ dias</div></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="text-2xl font-black">{items.reduce((a,x)=>a+(x.metaVariants||1),0)}</div><div className="mt-1 text-[10px] uppercase text-zinc-600">Variações Meta</div></div></div>
  <div className="mt-5 grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{filtered.map(x=><article key={x.captureId} className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/60">
   {x.images?.[0]?<img src={x.images[0]} className="h-44 w-full object-cover" onError={e=>e.currentTarget.style.display='none'}/>:<div className="grid h-32 place-items-center bg-zinc-950 text-zinc-800"><ImageIcon className="h-8 w-8"/></div>}
   <div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-widest text-blue-400">{x.searchQuery||'Meta Ads'}</div><h3 className="mt-1 truncate font-bold">{x.pageName}</h3></div><div className={`rounded-lg px-2 py-1 text-xs font-black ${x.score>=75?'bg-emerald-400/10 text-emerald-300':x.score>=55?'bg-blue-400/10 text-blue-300':'bg-amber-400/10 text-amber-300'}`}>{x.score}</div></div>
   <div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-zinc-950 p-2"><div className="font-bold">{x.days??'—'}</div><div className="text-[9px] text-zinc-600">dias</div></div><div className="rounded-lg bg-zinc-950 p-2"><div className="font-bold">{x.metaVariants||1}</div><div className="text-[9px] text-zinc-600">variações</div></div><div className="rounded-lg bg-zinc-950 p-2"><div className="font-bold">{x.images?.length||0}</div><div className="text-[9px] text-zinc-600">mídias</div></div></div>
   {x.adText&&<p className="mt-3 line-clamp-5 text-xs leading-relaxed text-zinc-400">{x.adText}</p>}
   <div className="mt-3 flex flex-wrap gap-1.5">{x.checkout&&<span className="rounded bg-amber-400/10 px-2 py-1 text-[10px] text-amber-300">Checkout</span>}{x.whatsapp&&<span className="rounded bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">WhatsApp</span>}{x.hasVideo&&<span className="rounded bg-purple-400/10 px-2 py-1 text-[10px] text-purple-300">Vídeo</span>}<span className="rounded bg-zinc-800 px-2 py-1 text-[10px] text-zinc-400">{x.tier}</span></div>
   <div className="mt-4 flex gap-2"><button onClick={()=>dossiers[x.captureId]?setDetail(dossiers[x.captureId]):investigate(x)} disabled={analyzing===x.captureId} className="flex-1 rounded-lg bg-fuchsia-500/10 px-3 py-2 text-center text-xs font-bold text-fuchsia-300 disabled:opacity-50">{analyzing===x.captureId?'Analisando...':dossiers[x.captureId]?'Ver dossiê':'Investigar'}</button><a href={metaSearch(x.pageName)} target="_blank" rel="noreferrer" className="flex-1 rounded-lg bg-blue-500/10 px-3 py-2 text-center text-xs font-bold text-blue-300">Ver na Meta</a>{x.destinations?.[0]&&<a href={x.destinations[0]} target="_blank" rel="noreferrer" className="rounded-lg border border-zinc-800 px-3 py-2 text-zinc-400"><ExternalLink className="h-4 w-4"/></a>}<button onClick={()=>remove(x.captureId)} className="rounded-lg border border-zinc-800 px-3 text-zinc-600 hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div>
   </div></article>)}</div>
  {!filtered.length&&<div className="mt-4 rounded-2xl border border-dashed border-zinc-800 py-16 text-center text-sm text-zinc-600">Nenhum anúncio selecionado ainda. Na Meta Ads Library, marque os anúncios interessantes e clique “Enviar selecionados ao Radar”.</div>}
  {detail&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4" onClick={()=>setDetail(null)}><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl border border-zinc-700 bg-zinc-950 p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-widest text-fuchsia-400">Dossiê automático</div><h2 className="mt-1 text-xl font-bold">{detail.title||detail.meta?.pageName}</h2><p className="mt-1 text-xs text-zinc-500">{detail.finalUrl||detail.url}</p></div><button onClick={()=>setDetail(null)} className="rounded-lg border border-zinc-800 px-3 py-2 text-xs">Fechar</button></div>
   <div className="mt-5 grid gap-2 sm:grid-cols-4"><div className="rounded-xl bg-zinc-900 p-3"><b className="text-xl">{detail.score}</b><div className="text-[10px] text-zinc-600">score técnico</div></div><div className="rounded-xl bg-zinc-900 p-3"><b className="text-xl">{detail.meta?.days??'—'}</b><div className="text-[10px] text-zinc-600">dias no anúncio</div></div><div className="rounded-xl bg-zinc-900 p-3"><b className="text-xl">{detail.meta?.metaVariants||1}</b><div className="text-[10px] text-zinc-600">variações Meta</div></div><div className="rounded-xl bg-zinc-900 p-3"><b className="text-xl">{detail.prices?.[0]||'—'}</b><div className="text-[10px] text-zinc-600">preço detectado</div></div></div>
   <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-zinc-800 p-4"><h3 className="font-semibold">Oferta & copy</h3><div className="mt-3 text-xs text-zinc-400"><b className="text-zinc-200">Headline:</b> {detail.h1?.[0]||'Não detectada'}</div><div className="mt-2 text-xs text-zinc-400"><b className="text-zinc-200">Descrição:</b> {detail.description||'Não detectada'}</div><div className="mt-3 flex flex-wrap gap-1">{(detail.ctas||[]).slice(0,8).map(v=><span key={v} className="rounded bg-zinc-900 px-2 py-1 text-[10px]">{v}</span>)}</div></div>
   <div className="rounded-xl border border-zinc-800 p-4"><h3 className="font-semibold">Estrutura do funil</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(detail.tech||{}).filter(([,v])=>v).map(([k])=><span key={k} className="rounded bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">{k}</span>)}</div><div className="mt-3 text-xs text-zinc-500">{detail.checkouts?.length?'Landing → Checkout':''}{detail.videos?.length?' • VSL/Vídeo':''}{detail.whatsapp?.length?' • WhatsApp':''}</div></div></div>
   {(detail.whatsapp||[]).some(w=>w.message)&&<div className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/[.05] p-4"><div className="text-xs font-bold text-emerald-300">Mensagem inicial do WhatsApp</div><div className="mt-2 text-sm">{detail.whatsapp.find(w=>w.message)?.message}</div></div>}
   <div className="mt-4 flex flex-wrap gap-2">{(detail.checkouts||[]).slice(0,3).map(u=><a key={u} href={u} target="_blank" rel="noreferrer" className="rounded-lg bg-amber-400/10 px-3 py-2 text-xs text-amber-300">Abrir checkout</a>)}<a href={detail.finalUrl||detail.url} target="_blank" rel="noreferrer" className="rounded-lg bg-blue-500/10 px-3 py-2 text-xs text-blue-300">Abrir landing</a></div>
  </div></div>}
 </div>
}