import {useState} from 'react'
import {ExternalLink,Trash2} from 'lucide-react'
const KEY='oferta-radar:offer-library'
export default function OfferLibrary(){
 const[items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}})
 const persist=n=>{setItems(n);localStorage.setItem(KEY,JSON.stringify(n))}
 const status=(id,s)=>persist(items.map(x=>x.id===id?{...x,status:s}:x))
 return <div><div className="mb-4"><h2 className="text-lg font-bold">Minhas Ofertas</h2><p className="mt-1 text-xs text-zinc-500">Biblioteca das ofertas analisadas e salvas neste navegador.</p></div>
 {items.length?<div className="grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{items.map(x=>{let d='';try{d=new URL(x.finalUrl).hostname.replace(/^www\./,'')}catch{};return <article key={x.id} className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="truncate text-xs font-bold text-fuchsia-400">{d}</div><h3 className="mt-1 line-clamp-2 font-bold">{x.title||x.h1?.[0]||'Oferta'}</h3></div><div className="rounded-lg bg-emerald-400/10 px-2 py-1 text-xs font-bold text-emerald-300">{x.score}/100</div></div><div className="mt-3 flex flex-wrap gap-1.5">{x.prices?.slice(0,3).map(p=><span key={p} className="rounded bg-amber-400/10 px-2 py-1 text-[10px] text-amber-300">{p}</span>)}</div><select value={x.status||'Em análise'} onChange={e=>status(x.id,e.target.value)} className="mt-4 w-full rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-xs"><option>Em análise</option><option>Promissora</option><option>Validada</option><option>Descartada</option></select><div className="mt-3 flex gap-2"><a href={x.finalUrl} target="_blank" rel="noreferrer" className="flex-1 rounded-lg border border-zinc-800 px-3 py-2 text-center text-xs">Abrir oferta</a><button onClick={()=>persist(items.filter(i=>i.id!==x.id))} className="rounded-lg border border-zinc-800 px-3 text-zinc-600 hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div></article>})}</div>:<div className="rounded-2xl border border-dashed border-zinc-800 py-16 text-center text-sm text-zinc-600">Nenhuma oferta salva ainda. Use o Analisador para criar sua primeira ficha.</div>}</div>
}