import {useState} from 'react'
import {Search,ExternalLink,Save,Loader2,CheckCircle2,MessageCircle,ShoppingCart,Video,MousePointerClick,Code2} from 'lucide-react'
const LIB='oferta-radar:offer-library'
const meta=q=>`https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q=${encodeURIComponent(q)}&search_type=keyword_unordered`
const Badge=({ok,children})=><span className={`rounded-lg border px-2.5 py-1 text-[11px] font-bold ${ok?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':'border-zinc-800 bg-zinc-900 text-zinc-600'}`}>{children}</span>
export default function OfferAnalyzer(){
 const[url,setUrl]=useState('');const[data,setData]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState(false)
 async function analyze(){if(!url.trim())return;setLoading(true);setError('');setData(null);setSaved(false);try{const r=await fetch(`/api/analyze?url=${encodeURIComponent(url.trim())}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na análise');setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 function save(){if(!data)return;let a=[];try{a=JSON.parse(localStorage.getItem(LIB)||'[]')}catch{};const item={...data,id:crypto.randomUUID(),status:'Em análise',savedAt:new Date().toISOString()};localStorage.setItem(LIB,JSON.stringify([item,...a]));setSaved(true)}
 const domain=data?(()=>{try{return new URL(data.finalUrl).hostname.replace(/^www\./,'')}catch{return''}})():''
 return <div>
  <section className="rounded-2xl border border-fuchsia-400/20 bg-gradient-to-br from-fuchsia-500/[.07] to-zinc-900/60 p-5">
   <div className="flex items-center gap-2"><Code2 className="h-5 w-5 text-fuchsia-400"/><h2 className="text-lg font-bold">Analisador de Oferta</h2><span className="rounded bg-fuchsia-500/15 px-2 py-1 text-[10px] font-bold text-fuchsia-300">FASE 4</span></div>
   <p className="mt-2 max-w-3xl text-xs leading-relaxed text-zinc-400">Cole a landing page encontrada em um anúncio. O backend lê o HTML e mapeia sinais de funil, tracking, VSL, checkout, WhatsApp, preços, headline e CTAs.</p>
   <div className="mt-5 flex flex-col gap-2 md:flex-row"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&analyze()} placeholder="https://landing-page.com/..." className="flex-1 rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-sm outline-none focus:border-fuchsia-400/50"/><button onClick={analyze} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-fuchsia-500 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Search className="h-4 w-4"/>}{loading?'Analisando...':'Analisar oferta'}</button></div>
  </section>
  {error&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}
  {data&&<div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]">
   <div className="space-y-4">
    <section className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/60">
     {data.ogImage&&<img src={data.ogImage} className="h-52 w-full object-cover" onError={e=>e.currentTarget.style.display='none'}/>}
     <div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="text-xs font-bold uppercase tracking-widest text-fuchsia-400">{domain}</div><h3 className="mt-1 text-xl font-bold">{data.title||data.h1?.[0]||'Oferta sem título'}</h3><p className="mt-2 max-w-3xl text-sm text-zinc-400">{data.description}</p></div><div className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-2 text-center"><div className="text-2xl font-black text-emerald-300">{data.score}</div><div className="text-[9px] font-bold uppercase text-emerald-400/70">Score técnico</div></div></div>
     <div className="mt-5 flex flex-wrap gap-2"><Badge ok={data.tech.metaPixel}>Meta Pixel</Badge><Badge ok={data.tech.googleAnalytics}>Google Tracking</Badge><Badge ok={data.tech.utm}>UTM/Click ID</Badge><Badge ok={data.tech.video}>VSL/Vídeo</Badge><Badge ok={data.tech.checkout}>Checkout</Badge><Badge ok={data.tech.whatsapp}>WhatsApp</Badge></div></div>
    </section>
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><h3 className="font-semibold">Copy & Oferta</h3><div className="mt-4 space-y-4">{data.h1?.length>0&&<div><div className="text-[10px] font-bold uppercase tracking-widest text-zinc-600">Headlines</div>{data.h1.map((x,i)=><div key={i} className="mt-2 rounded-lg bg-zinc-950 p-3 text-sm">{x}</div>)}</div>}{data.prices?.length>0&&<div><div className="text-[10px] font-bold uppercase tracking-widest text-zinc-600">Preços detectados</div><div className="mt-2 flex flex-wrap gap-2">{data.prices.map(x=><span key={x} className="rounded-lg bg-amber-400/10 px-3 py-2 text-sm font-bold text-amber-300">{x}</span>)}</div></div>}{data.ctas?.length>0&&<div><div className="text-[10px] font-bold uppercase tracking-widest text-zinc-600">CTAs</div><div className="mt-2 flex flex-wrap gap-2">{data.ctas.map((x,i)=><span key={i} className="rounded-lg border border-zinc-800 px-3 py-2 text-xs text-zinc-300">{x}</span>)}</div></div>}</div></section>
    {data.whatsapp?.length>0&&<section className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-5"><div className="flex items-center gap-2"><MessageCircle className="h-4 w-4 text-emerald-400"/><h3 className="font-semibold">WhatsApp encontrado</h3></div>{data.whatsapp.map((w,i)=><div key={i} className="mt-3 rounded-xl bg-zinc-950 p-3"><a href={w.url} target="_blank" rel="noreferrer" className="text-xs text-emerald-400">Abrir WhatsApp</a>{w.message&&<div className="mt-2 text-sm text-zinc-300">“{w.message}”</div>}</div>)}</section>}
   </div>
   <aside className="space-y-4">
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><h3 className="font-semibold">Mapa do funil</h3><div className="mt-4 space-y-2 text-xs"><div className="rounded-xl bg-blue-500/10 p-3 text-blue-300">Meta Ads / Origem</div><div className="pl-4 text-zinc-700">↓</div><div className="rounded-xl bg-zinc-950 p-3">{domain}</div>{data.tech.video&&<><div className="pl-4 text-zinc-700">↓</div><div className="rounded-xl bg-purple-500/10 p-3 text-purple-300">VSL / Vídeo</div></>}{data.tech.checkout&&<><div className="pl-4 text-zinc-700">↓</div><div className="rounded-xl bg-amber-500/10 p-3 text-amber-300">Checkout detectado</div></>}{data.tech.whatsapp&&<><div className="pl-4 text-zinc-700">↘</div><div className="rounded-xl bg-emerald-500/10 p-3 text-emerald-300">WhatsApp</div></>}</div></section>
    {data.checkouts?.length>0&&<section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-5"><div className="flex items-center gap-2"><ShoppingCart className="h-4 w-4 text-amber-400"/><h3 className="font-semibold">Checkout</h3></div>{data.checkouts.slice(0,5).map((x,i)=><a key={i} href={x} target="_blank" rel="noreferrer" className="mt-3 block truncate text-xs text-amber-300 hover:underline">{x}</a>)}</section>}
    <section className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-4 space-y-2"><a href={meta(domain)} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-4 py-3 text-xs font-bold text-white">Buscar domínio na Meta <ExternalLink className="h-3.5 w-3.5"/></a><a href={data.finalUrl} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-xl border border-zinc-700 px-4 py-3 text-xs font-bold">Abrir landing <ExternalLink className="h-3.5 w-3.5"/></a><button onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-xs font-bold text-emerald-300">{saved?<CheckCircle2 className="h-4 w-4"/>:<Save className="h-4 w-4"/>}{saved?'Salva em Minhas Ofertas':'Salvar oferta'}</button></section>
   </aside>
  </div>}
 </div>
}